# Do not forget to create the .env file (see template)
# before using this container!


services:
    sensors-report:
        restart: always
        build: .
        env_file:
            - .env
        environment:
          MQTT_HOST: $MQTT_HOST
          MQTT_PREFIX: $MQTT_PREFIX
        volumes:
            - /tmp:/tmp:r

